#!/usr/bin/env bash
#A Bash script that generates a MySQL dump and
#creates a compressed archive out of it
mysqldump -u root -p"$1" --all-databases > backup.sql
#creates an archive
now=$(date +"%d-%m-%Y")
tar -czf "$now.tar.gz" backup.sql
