#!/usr/bin/env bash

# This script is displaying "Holberton School" 10 times
# and "Hi" for the 9th iteration

i=0
while [ $i -lt 11 ]
do
	if [ $i = 9 ]
        then
	    echo "Hi"
	else
	    echo "Holberton School"
	fi
	(( i++ ))
done
