#!/usr/bin/env bash
# Bash Script that configures the container so that Nginx is running as
# the nginx user
pkill -f apache2
chown -R nginx /etc/nginx
chmod 777 /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
