#!/usr/bin/env bash
# A short Bash Script that configures Nginx to run as user
pkill -f apache2
chown -R nginx /etc/nginx
chmod 777 /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
